name: Publish to npm
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write 

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          
          npm run build

          npm version patch --no-git-tag-version
          VERSION=$(node -p 'require("./package.json").version')
          echo $VERSION

          if npm view $(node -p 'require("./package.json").name')@${VERSION} > /dev/null 2>&1; then
            echo Version $VERSION already exists on npm. Skipping publish.
            exit 0
          fi

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json package-lock.json || true 
          git commit -m "chore(release): v$VERSION" || true
          git tag v$VERSION

          npm publish

          git push origin ${{ github.event.pull_request.base.ref }} --follow-tags
